permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm install
      - run: npm run build
      - name: Run collector
        env:
          BRAPI_TOKEN: ${{ secrets.BRAPI_TOKEN }}
        run: node dist/index.js
      - name: Commit & push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/all.json
          git commit -m "update data [skip ci]" || echo "no changes"
          git push
